#!/usr/bin/env python3
"""
Email Service for HR Tech Lead Generation System
Handles email sending and report generation
"""

import logging
import os
import smtplib
from datetime import datetime
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, List, Optional

from constants import SIGNAL_TYPES

logger = logging.getLogger(__name__)


def build_html_table(opportunities: List[Any]) -> str:
    """Build HTML table for email report"""
    table_rows = []

    for idx, opp in enumerate(opportunities, start=1):
        signal_name = SIGNAL_TYPES.get(opp.signal_type, "Unknown signal")
        email_value = opp.email if opp.email else "Needs lookup"
        person_value = opp.person if opp.person else "N/A"
        url_value = opp.url if opp.url else ""

        url_display = url_value[:50] + "..." if len(url_value) > 50 else url_value
        url_link = f'<a href="{url_value}">{url_display}</a>' if url_value else "N/A"

        table_rows.append(f"""
            <tr>
                <td style="border: 1px solid #ddd; padding: 8px; text-align: center;">{idx}</td>
                <td style="border: 1px solid #ddd; padding: 8px; font-weight: bold;">{opp.company}</td>
                <td style="border: 1px solid #ddd; padding: 8px;">{signal_name}</td>
                <td style="border: 1px solid #ddd; padding: 8px;">{person_value}</td>
                <td style="border: 1px solid #ddd; padding: 8px;"><a href="mailto:{email_value}">{email_value}</a></td>
                <td style="border: 1px solid #ddd; padding: 8px; font-size: 11px;">{url_link}</td>
            </tr>
        """)

    return f"""
        <p>Generated <strong>{len(opportunities)}</strong> opportunities.</p>
        <table style="border-collapse: collapse; width: 100%; margin: 20px 0; font-family: Arial, sans-serif; font-size: 13px;">
            <thead>
                <tr style="background-color: #4CAF50; color: white;">
                    <th style="border: 1px solid #ddd; padding: 12px; text-align: left;">#</th>
                    <th style="border: 1px solid #ddd; padding: 12px; text-align: left;">Company</th>
                    <th style="border: 1px solid #ddd; padding: 12px; text-align: left;">Signal Type</th>
                    <th style="border: 1px solid #ddd; padding: 12px; text-align: left;">Contact</th>
                    <th style="border: 1px solid #ddd; padding: 12px; text-align: left;">Email</th>
                    <th style="border: 1px solid #ddd; padding: 12px; text-align: left;">URL</th>
                </tr>
            </thead>
            <tbody>
                {''.join(table_rows)}
            </tbody>
        </table>
    """


def build_html_email_body(opportunities: List[Any], report_date: str) -> str:
    """Build complete HTML email body"""
    html_table = build_html_table(opportunities)

    return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                .container {{ max-width: 1000px; margin: 0 auto; padding: 20px; }}
                .header {{ background-color: #f4f4f4; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
                .footer {{ margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h2 style="margin: 0; color: #2c3e50;">Daily HR Tech Lead Generation Report</h2>
                    <p style="margin: 5px 0 0 0; color: #7f8c8d;">Generated on {report_date}</p>
                </div>

                <p>Hello Ariel,</p>
                <p>Here are the latest HR tech opportunities:</p>

                {html_table}

                <div class="footer">
                    <p>This update was automatically generated by your HR Tech Lead Generation System.</p>
                </div>
            </div>
        </body>
        </html>
    """


def build_plain_text_body(opportunities: List[Any], report_date: str) -> str:
    """Build plain text email body"""
    plain_body = f"""
Hello Ariel,

Here are the latest HR tech opportunities generated on {report_date}.

Generated {len(opportunities)} opportunities.

Opportunities:
"""
    plain_body += "\n"
    plain_body += f"{'#':<4} {'Company':<30} {'Signal Type':<30} {'Contact':<25} {'Email':<35}\n"
    plain_body += "-" * 130 + "\n"

    for idx, opp in enumerate(opportunities, start=1):
        signal_name = SIGNAL_TYPES.get(opp.signal_type, "Unknown signal")
        email_value = opp.email if opp.email else "Needs lookup"
        person_value = opp.person if opp.person else "N/A"
        company_short = opp.company[:28] if len(opp.company) > 28 else opp.company
        signal_short = signal_name[:28] if len(signal_name) > 28 else signal_name
        person_short = person_value[:23] if len(person_value) > 23 else person_value
        email_short = email_value[:33] if len(email_value) > 33 else email_value
        plain_body += f"{idx:<4} {company_short:<30} {signal_short:<30} {person_short:<25} {email_short:<35}\n"
        if opp.url:
            plain_body += f"     URL: {opp.url}\n"

    plain_body += "\n---\nThis update was automatically generated by your HR Tech Lead Generation System."

    return plain_body


def send_email_report(
    email_config: Dict[str, Any],
    report_content: str,
    csv_file_path: Optional[str] = None,
    email_subject: str = "daily leads",
    opportunities: Optional[List[Any]] = None,
) -> bool:
    """Send the report via email with HTML table format"""
    if not email_config:
        logger.error("Email configuration not found")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["From"] = email_config["sender_email"]
        msg["To"] = email_config["recipient_email"]
        msg["Subject"] = email_subject

        report_date = datetime.now().strftime('%Y-%m-%d at %H:%M')

        if opportunities:
            html_body = build_html_email_body(opportunities, report_date)
            plain_body = build_plain_text_body(opportunities, report_date)
            msg.attach(MIMEText(plain_body, "plain"))
            msg.attach(MIMEText(html_body, "html"))
        else:
            body = f"""
Hello Ariel,

Here are the latest HR tech opportunities generated on {report_date}.

{report_content}

---
This update was automatically generated by your HR Tech Lead Generation System.
            """
            msg.attach(MIMEText(body, "plain"))

        # Attach CSV file if provided
        if csv_file_path and os.path.exists(csv_file_path):
            with open(csv_file_path, "rb") as attachment:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename= {os.path.basename(csv_file_path)}",
                )
                msg.attach(part)

        # Connect and send
        server = smtplib.SMTP(email_config["smtp_server"], email_config["smtp_port"])
        server.starttls()
        server.login(email_config["sender_email"], email_config["sender_password"])

        text = msg.as_string()
        server.sendmail(
            email_config["sender_email"], email_config["recipient_email"], text
        )
        server.quit()

        logger.info(f"Email report sent successfully to {email_config['recipient_email']}")
        return True

    except Exception as e:
        logger.error(f"Failed to send email report: {e}")
        return False


def summarize_opportunities(opportunities: List[Any], target: int) -> str:
    """Build a human-readable summary for email reports"""
    if not opportunities:
        return "No opportunities were generated during this run."

    lines = [
        f"Generated {len(opportunities)} opportunities toward a target of {target}.",
        "",
        "Opportunities:",
    ]

    for idx, opp in enumerate(opportunities, start=1):
        signal_name = SIGNAL_TYPES.get(opp.signal_type, "Unknown signal")
        email_value = opp.email if opp.email else "Needs lookup"
        lines.append(
            f"{idx}. {opp.company} - {signal_name} | Contact: {opp.person or 'N/A'} | Email: {email_value}"
        )
        if opp.url:
            lines.append(f"   URL: {opp.url}")

    return "\n".join(lines)
